<?php

/**
 * mime_types.php
 * 
 * This file contains function used to handle files correctly. File type are determined via 
 * finfo (if installed) or matching included array.
 * 
 * @package		Comodojo ServerSide Core Packages
 * @author		comodojo.org
 * @copyright	__COPYRIGHT__ comodojo.org (info@comodojo.org)
 * @version		__CURRENT_VERSION__
 * @license		GPL Version 3
*/

$comodojo_mimeTypes = Array(
	"323"	=>	Array("mime"=>"text/h323",	"icon"=>"application_octet_stream.png"),
	"acx"	=>	Array("mime"=>"application/internet-property-stream",	"icon"=>"application_octet_stream.png"),
	"ai"	=>	Array("mime"=>"application/postscript",	"icon"=>"application_octet_stream.png"),
	"aif"	=>	Array("mime"=>"audio/x-aiff",	"icon"=>"audio_basic.png"),
	"aifc"	=>	Array("mime"=>"audio/x-aiff",	"icon"=>"audio_basic.png"),
	"aiff"	=>	Array("mime"=>"audio/x-aiff",	"icon"=>"audio_basic.png"),
	"asf"	=>	Array("mime"=>"video/x-ms-asf",	"icon"=>"video.png"),
	"asr"	=>	Array("mime"=>"video/x-ms-asf",	"icon"=>"video.png"),
	"asx"	=>	Array("mime"=>"video/x-ms-asf",	"icon"=>"video.png"),
	"au"	=>	Array("mime"=>"audio/basic",	"icon"=>"audio_basic.png"),
	"avi"	=>	Array("mime"=>"video/x-msvideo",	"icon"=>"video.png"),
	"axs"	=>	Array("mime"=>"application/olescript",	"icon"=>"application_octet_stream.png"),
	"bas"	=>	Array("mime"=>"text/plain",	"icon"=>"text_plain.png"),
	"bcpio"	=>	Array("mime"=>"application/x-bcpio",	"icon"=>"application_octet_stream.png"),
	"bin"	=>	Array("mime"=>"application/octet-stream",	"icon"=>"application_octet_stream.png"),
	"bmp"	=>	Array("mime"=>"image/bmp",	"icon"=>"image_x_generic.png"),
	"c"		=>	Array("mime"=>"text/plain",	"icon"=>"text_plain.png"),
	"cat"	=>	Array("mime"=>"application/vnd.ms-pkiseccat",	"icon"=>"application_octet_stream.png"),
	"cdf"	=>	Array("mime"=>"application/x-cdf",	"icon"=>"application_octet_stream.png"),
	"cer"	=>	Array("mime"=>"application/x-x509-ca-cert",	"icon"=>"application_octet_stream.png"),
	"class"	=>	Array("mime"=>"application/octet-stream",	"icon"=>"application_octet_stream.png"),
	"clp"	=>	Array("mime"=>"application/x-msclip",	"icon"=>"application_octet_stream.png"),
	"cmx"	=>	Array("mime"=>"image/x-cmx",	"icon"=>"image_x_generic.png"),
	"cod"	=>	Array("mime"=>"image/cis-cod",	"icon"=>"image_x_generic.png"),
	"cpio"	=>	Array("mime"=>"application/x-cpio",	"icon"=>"application_octet_stream.png"),
	"crd"	=>	Array("mime"=>"application/x-mscardfile",	"icon"=>"application_octet_stream.png"),
	"crl"	=>	Array("mime"=>"application/pkix-crl",	"icon"=>"application_octet_stream.png"),
	"crt"	=>	Array("mime"=>"application/x-x509-ca-cert",	"icon"=>"application_octet_stream.png"),
	"csh"	=>	Array("mime"=>"application/x-csh",	"icon"=>"application_octet_stream.png"),
	"css"	=>	Array("mime"=>"text/css",	"icon"=>"text_css.png"),
	"csv"	=>	Array("mime"=>"text/csv",	"icon"=>"text_csv.png"),
	"dcr"	=>	Array("mime"=>"application/x-director",	"icon"=>"application_octet_stream.png"),
	"der"	=>	Array("mime"=>"application/x-x509-ca-cert",	"icon"=>"application_octet_stream.png"),
	"dir"	=>	Array("mime"=>"application/x-director",	"icon"=>"application_octet_stream.png"),
	"dll"	=>	Array("mime"=>"application/x-msdownload",	"icon"=>"application_octet_stream.png"),
	"dms"	=>	Array("mime"=>"application/octet-stream",	"icon"=>"application_octet_stream.png"),
	"doc"	=>	Array("mime"=>"application/msword",	"icon"=>"application_vnd.ms_word.png"),
	"dot"	=>	Array("mime"=>"application/msword",	"icon"=>"application_vnd.ms_word.png"),
	"dvi"	=>	Array("mime"=>"application/x-dvi",	"icon"=>"application_octet_stream.png"),
	"dxr"	=>	Array("mime"=>"application/x-director",	"icon"=>"application_octet_stream.png"),
	"eps"	=>	Array("mime"=>"application/postscript",	"icon"=>"application_octet_stream.png"),
	"etx"	=>	Array("mime"=>"text/x-setext",	"icon"=>"text_plain.png"),
	"evy"	=>	Array("mime"=>"application/envoy",	"icon"=>"application_octet_stream.png"),
	"exe"	=>	Array("mime"=>"application/octet-stream",	"icon"=>"application_octet_stream.png"),
	"fif"	=>	Array("mime"=>"application/fractals",	"icon"=>"application_octet_stream.png"),
	"flr"	=>	Array("mime"=>"x-world/x-vrml",	"icon"=>"application_octet_stream.png"),
	"gif"	=>	Array("mime"=>"image/gif",	"icon"=>"image_x_generic.png"),
	"gtar"	=>	Array("mime"=>"application/x-gtar",	"icon"=>"application_octet_stream.png"),
	"gz"	=>	Array("mime"=>"application/x-gzip",	"icon"=>"application_octet_stream.png"),
	"h"		=>	Array("mime"=>"text/plain",	"icon"=>"text_plain.png"),
	"hdf"	=>	Array("mime"=>"application/x-hdf",	"icon"=>"application_octet_stream.png"),
	"hlp"	=>	Array("mime"=>"application/winhlp",	"icon"=>"application_octet_stream.png"),
	"hqx"	=>	Array("mime"=>"application/mac-binhex40",	"icon"=>"application_octet_stream.png"),
	"hta"	=>	Array("mime"=>"application/hta",	"icon"=>"application_octet_stream.png"),
	"htc"	=>	Array("mime"=>"text/x-component",	"icon"=>"text_plain.png"),
	"htm"	=>	Array("mime"=>"text/html",	"icon"=>"text_html.png"),
	"html"	=>	Array("mime"=>"text/html",	"icon"=>"text_html.png"),
	"htt"	=>	Array("mime"=>"text/webviewhtml",	"icon"=>"text_html.png"),
	"ico"	=>	Array("mime"=>"image/x-icon",	"icon"=>"image_x_generic.png"),
	"ief"	=>	Array("mime"=>"image/ief",	"icon"=>"image_x_generic.png"),
	"iii"	=>	Array("mime"=>"application/x-iphone",	"icon"=>"application_octet_stream.png"),
	"ins"	=>	Array("mime"=>"application/x-internet-signup",	"icon"=>"application_octet_stream.png"),
	"isp"	=>	Array("mime"=>"application/x-internet-signup",	"icon"=>"application_octet_stream.png"),
	"jfif"	=>	Array("mime"=>"image/pipeg",	"icon"=>"image_x_generic.png"),
	"jpe"	=>	Array("mime"=>"image/jpeg",	"icon"=>"image_x_generic.png"),
	"jpeg"	=>	Array("mime"=>"image/jpeg",	"icon"=>"image_x_generic.png"),
	"jpg"	=>	Array("mime"=>"image/jpeg",	"icon"=>"image_x_generic.png"),
	"js"	=>	Array("mime"=>"application/x-javascript",	"icon"=>"application_x_javascript.png"),
	"json"	=>	Array("mime"=>"application/json",	"icon"=>"application_octet_stream.png"),
	"latex"	=>	Array("mime"=>"application/x-latex",	"icon"=>"application_octet_stream.png"),
	"lha"	=>	Array("mime"=>"application/octet-stream",	"icon"=>"application_octet_stream.png"),
	"lsf"	=>	Array("mime"=>"video/x-la-asf",	"icon"=>"video.png"),
	"lsx"	=>	Array("mime"=>"video/x-la-asf",	"icon"=>"video.png"),
	"lzh"	=>	Array("mime"=>"application/octet-stream",	"icon"=>"application_x_archive.png"),
	"m13"	=>	Array("mime"=>"application/x-msmediaview",	"icon"=>"application_octet_stream.png"),
	"m14"	=>	Array("mime"=>"application/x-msmediaview",	"icon"=>"application_octet_stream.png"),
	"m3u"	=>	Array("mime"=>"audio/x-mpegurl",	"icon"=>"audio_basic.png"),
	"man"	=>	Array("mime"=>"application/x-troff-man",	"icon"=>"application_octet_stream.png"),
	"mdb"	=>	Array("mime"=>"application/x-msaccess",	"icon"=>"application_octet_stream.png"),
	"me"	=>	Array("mime"=>"application/x-troff-me",	"icon"=>"application_octet_stream.png"),
	"mht"	=>	Array("mime"=>"message/rfc822",	"icon"=>"application_octet_stream.png"),
	"mhtml"	=>	Array("mime"=>"message/rfc822",	"icon"=>"application_octet_stream.png"),
	"mid"	=>	Array("mime"=>"audio/mid",	"icon"=>"audio_basic.png"),
	"mny"	=>	Array("mime"=>"application/x-msmoney",	"icon"=>"application_octet_stream.png"),
	"mov"	=>	Array("mime"=>"video/quicktime",	"icon"=>"video.png"),
	"movie"	=>	Array("mime"=>"video/x-sgi-movie",	"icon"=>"video.png"),
	"mp2"	=>	Array("mime"=>"video/mpeg",	"icon"=>"video.png"),
	"mp3"	=>	Array("mime"=>"audio/mpeg",	"icon"=>"audio_basic.png"),
	"mpa"	=>	Array("mime"=>"video/mpeg",	"icon"=>"video.png"),
	"mpe"	=>	Array("mime"=>"video/mpeg",	"icon"=>"video.png"),
	"mpeg"	=>	Array("mime"=>"video/mpeg",	"icon"=>"video.png"),
	"mpg"	=>	Array("mime"=>"video/mpeg",	"icon"=>"video.png"),
	"mpp"	=>	Array("mime"=>"application/vnd.ms-project",	"icon"=>"application_octet_stream.png"),
	"mpv2"	=>	Array("mime"=>"video/mpeg",	"icon"=>"video.png"),
	"ms"	=>	Array("mime"=>"application/x-troff-ms",	"icon"=>"application_octet_stream.png"),
	"mvb"	=>	Array("mime"=>"application/x-msmediaview",	"icon"=>"application_octet_stream.png"),
	"nws"	=>	Array("mime"=>"message/rfc822",	"icon"=>"application_octet_stream.png"),
	"oda"	=>	Array("mime"=>"application/oda",	"icon"=>"application_octet_stream.png"),
	"p10"	=>	Array("mime"=>"application/pkcs10",	"icon"=>"application_octet_stream.png"),
	"p12"	=>	Array("mime"=>"application/x-pkcs12",	"icon"=>"application_octet_stream.png"),
	"p7b"	=>	Array("mime"=>"application/x-pkcs7-certificates",	"icon"=>"application_octet_stream.png"),
	"p7c"	=>	Array("mime"=>"application/x-pkcs7-mime",	"icon"=>"application_octet_stream.png"),
	"p7m"	=>	Array("mime"=>"application/x-pkcs7-mime",	"icon"=>"application_octet_stream.png"),
	"p7r"	=>	Array("mime"=>"application/x-pkcs7-certreqresp",	"icon"=>"application_octet_stream.png"),
	"p7s"	=>	Array("mime"=>"application/x-pkcs7-signature",	"icon"=>"application_octet_stream.png"),
	"pbm"	=>	Array("mime"=>"image/x-portable-bitmap",	"icon"=>"image_x_generic.png"),
	"pdf"	=>	Array("mime"=>"application/pdf",	"icon"=>"application_pdf.png"),
	"pfx"	=>	Array("mime"=>"application/x-pkcs12",	"icon"=>"application_octet_stream.png"),
	"pgm"	=>	Array("mime"=>"image/x-portable-graymap",	"icon"=>"image_x_generic.png"),
	"php"	=>	Array("mime"=>"application/x-php",	"icon"=>"application_x_php.png"),
	"pko"	=>	Array("mime"=>"application/ynd.ms-pkipko",	"icon"=>"application_octet_stream.png"),
	"pma"	=>	Array("mime"=>"application/x-perfmon",	"icon"=>"application_octet_stream.png"),
	"pmc"	=>	Array("mime"=>"application/x-perfmon",	"icon"=>"application_octet_stream.png"),
	"pml"	=>	Array("mime"=>"application/x-perfmon",	"icon"=>"application_octet_stream.png"),
	"pmr"	=>	Array("mime"=>"application/x-perfmon",	"icon"=>"application_octet_stream.png"),
	"pmw"	=>	Array("mime"=>"application/x-perfmon",	"icon"=>"application_octet_stream.png"),
	"pnm"	=>	Array("mime"=>"image/x-portable-anymap",	"icon"=>"image_x_generic.png"),
	"pot"	=>	Array("mime"=>"application/vnd.ms-powerpoint",	"icon"=>"application_vnd.ms_powerpoint.png"),
	"ppm"	=>	Array("mime"=>"image/x-portable-pixmap",	"icon"=>"image_x_generic.png"),
	"pps"	=>	Array("mime"=>"application/vnd.ms-powerpoint",	"icon"=>"application_vnd.ms_powerpoint.png"),
	"ppt"	=>	Array("mime"=>"application/vnd.ms-powerpoint",	"icon"=>"application_vnd.ms_powerpoint.png"),
	"prf"	=>	Array("mime"=>"application/pics-rules",	"icon"=>"application_octet_stream.png"),
	"ps"	=>	Array("mime"=>"application/postscript",	"icon"=>"application_octet_stream.png"),
	"pub"	=>	Array("mime"=>"appfile_inlication/x-mspublisher",	"icon"=>"application_octet_stream.png"),
	"qt"	=>	Array("mime"=>"video/quicktime",	"icon"=>"video.png"),
	"ra"	=>	Array("mime"=>"audio/x-pn-realaudio",	"icon"=>"audio_basic.png"),
	"ram"	=>	Array("mime"=>"audio/x-pn-realaudio",	"icon"=>"audio_basic.png"),
	"ras"	=>	Array("mime"=>"image/x-cmu-raster",	"icon"=>"image_x_generic.png"),
	"rgb"	=>	Array("mime"=>"image/x-rgb",	"icon"=>"image_x_generic.png"),
	"rmi"	=>	Array("mime"=>"audio/mid",	"icon"=>"audio_basic.png"),
	"roff"	=>	Array("mime"=>"application/x-troff",	"icon"=>"application_octet_stream.png"),
	"rtf"	=>	Array("mime"=>"application/rtf",	"icon"=>"text_rtf.png"),
	"rtx"	=>	Array("mime"=>"text/richtext",	"icon"=>"text_rtf.png"),
	"scd"	=>	Array("mime"=>"application/x-msschedule",	"icon"=>"application_octet_stream.png"),
	"sct"	=>	Array("mime"=>"text/scriptlet",	"icon"=>"text_plain.png"),
	"setpay"=>	Array("mime"=>"application/set-payment-initiation",	"icon"=>"application_octet_stream.png"),
	"setreg"=>	Array("mime"=>"application/set-registration-initiation",	"icon"=>"application_octet_stream.png"),
	"sh"	=>	Array("mime"=>"application/x-sh",	"icon"=>"application_octet_stream.png"),
	"shar"	=>	Array("mime"=>"application/x-shar",	"icon"=>"application_octet_stream.png"),
	"sit"	=>	Array("mime"=>"application/x-stuffit",	"icon"=>"application_octet_stream.png"),
	"snd"	=>	Array("mime"=>"audio/basic",	"icon"=>"audio_basic.png"),
	"spc"	=>	Array("mime"=>"application/x-pkcs7-certificates",	"icon"=>"application_octet_stream.png"),
	"spl"	=>	Array("mime"=>"application/futuresplash",	"icon"=>"application_octet_stream.png"),
	"src"	=>	Array("mime"=>"application/x-wais-source",	"icon"=>"application_octet_stream.png"),
	"sst"	=>	Array("mime"=>"application/vnd.ms-pkicertstore",	"icon"=>"application_octet_stream.png"),
	"stl"	=>	Array("mime"=>"application/vnd.ms-pkistl",	"icon"=>"application_octet_stream.png"),
	"stm"	=>	Array("mime"=>"text/html",	"icon"=>"text_html.png"),
	"sv4cpio"=>	Array("mime"=>"application/x-sv4cpio",	"icon"=>"application_octet_stream.png"),
	"sv4crc"=>	Array("mime"=>"application/x-sv4crc",	"icon"=>"application_octet_stream.png"),
	"t"		=>	Array("mime"=>"application/x-troff",	"icon"=>"application_octet_stream.png"),
	"tar"	=>	Array("mime"=>"application/x-tar",	"icon"=>"application_x_archive.png"),
	"tcl"	=>	Array("mime"=>"application/x-tcl",	"icon"=>"application_octet_stream.png"),
	"tex"	=>	Array("mime"=>"application/x-tex",	"icon"=>"application_octet_stream.png"),
	"texi"	=>	Array("mime"=>"application/x-texinfo",	"icon"=>"application_octet_stream.png"),
	"texinfo"=>	Array("mime"=>"application/x-texinfo",	"icon"=>"application_octet_stream.png"),
	"tgz"	=>	Array("mime"=>"application/x-compressed",	"icon"=>"application_x_archive.png"),
	"tif"	=>	Array("mime"=>"image/tiff",	"icon"=>"image_x_generic.png"),
	"tiff"	=>	Array("mime"=>"image/tiff",	"icon"=>"image_x_generic.png"),
	"tr"	=>	Array("mime"=>"application/x-troff",	"icon"=>"application_octet_stream.png"),
	"trm"	=>	Array("mime"=>"application/x-msterminal",	"icon"=>"application_octet_stream.png"),
	"tsv"	=>	Array("mime"=>"text/tab-separated-values",	"icon"=>"text_csv.png"),
	"txt"	=>	Array("mime"=>"text/plain",	"icon"=>"text_plain.png"),
	"uls"	=>	Array("mime"=>"text/iuls",	"icon"=>"text_plain.png"),
	"ustar"	=>	Array("mime"=>"application/x-ustar",	"icon"=>"application_octet_stream.png"),
	"vcf"	=>	Array("mime"=>"text/x-vcard",	"icon"=>"text_x_vcard.png"),
	"vrml"	=>	Array("mime"=>"x-world/x-vrml",	"icon"=>"application_octet_stream.png"),
	"wav"	=>	Array("mime"=>"audio/x-wav",	"icon"=>"audio_basic.png"),
	"wcm"	=>	Array("mime"=>"application/vnd.ms-works",	"icon"=>"application_octet_stream.png"),
	"wdb"	=>	Array("mime"=>"application/vnd.ms-works",	"icon"=>"application_octet_stream.png"),
	"wks"	=>	Array("mime"=>"application/vnd.ms-works",	"icon"=>"application_octet_stream.png"),
	"wma"	=>	Array("mime"=>"audio/x-ms-wma",	"icon"=>"audio_basic.png"),
	"wmf"	=>	Array("mime"=>"application/x-msmetafile",	"icon"=>"application_octet_stream.png"),
	"wmv"	=>	Array("mime"=>"video/x-ms-wmv",	"icon"=>"video.png"),
	"wps"	=>	Array("mime"=>"application/vnd.ms-works",	"icon"=>"application_octet_stream.png"),
	"wri"	=>	Array("mime"=>"application/x-mswrite",	"icon"=>"application_octet_stream.png"),
	"wrl"	=>	Array("mime"=>"x-world/x-vrml",	"icon"=>"application_octet_stream.png"),
	"wrz"	=>	Array("mime"=>"x-world/x-vrml",	"icon"=>"application_octet_stream.png"),
	"xaf"	=>	Array("mime"=>"x-world/x-vrml",	"icon"=>"application_octet_stream.png"),
	"xbm"	=>	Array("mime"=>"image/x-xbitmap",	"icon"=>"image_x_generic.png"),
	"xla"	=>	Array("mime"=>"application/vnd.ms-excel",	"icon"=>"application_vnd.ms_excel.png"),
	"xlc"	=>	Array("mime"=>"application/vnd.ms-excel",	"icon"=>"application_vnd.ms_excel.png"),
	"xlm"	=>	Array("mime"=>"application/vnd.ms-excel",	"icon"=>"application_vnd.ms_excel.png"),
	"xls"	=>	Array("mime"=>"application/vnd.ms-excel",	"icon"=>"application_vnd.ms_excel.png"),
	"xlt"	=>	Array("mime"=>"application/vnd.ms-excel",	"icon"=>"application_vnd.ms_excel.png"),
	"xlw"	=>	Array("mime"=>"application/vnd.ms-excel",	"icon"=>"application_vnd.ms_excel.png"),
	"xml"	=>	Array("mime"=>"application/xml",	"icon"=>"application_vnd.ms_excel.png"),
	"xof"	=>	Array("mime"=>"x-world/x-vrml",	"icon"=>"application_octet_stream.png"),
	"xpm"	=>	Array("mime"=>"image/x-xpixmap",	"icon"=>"image_x_generic.png"),
	"xwd"	=>	Array("mime"=>"image/x-xwindowdump",	"icon"=>"image_x_generic.png"),
	"z"		=>	Array("mime"=>"application/x-compress",	"icon"=>"application_x_archive.png"),
	"zip"	=>	Array("mime"=>"application/zip",	"icon"=>"application_x_archive.png")
);

$comodojo_mimeIcons = Array(
	"application/envoy"						=>	"application_octet_stream.png",
	"application/fractals"					=>	"application_octet_stream.png",
	"application/futuresplash"				=>	"application_octet_stream.png",
	"application/hta"						=>	"application_octet_stream.png",
	"application/internet-property-stream"	=>	"application_octet_stream.png",
	"application/json"						=>	"application_octet_stream.png",
	"application/mac-binhex40"				=>	"application_octet_stream.png",
	"application/msword"					=>	"application_vnd.ms_word.png",
	"application/octet-stream"				=>	"application_octet_stream.png",
	"application/oda"						=>	"application_octet_stream.png",
	"application/olescript"					=>	"application_octet_stream.png",
	"application/pdf"						=>	"application_pdf.png",
	"application/pics-rules"				=>	"application_octet_stream.png",
	"application/pkcs10"					=>	"application_octet_stream.png",
	"application/pkix-crl"					=>	"application_octet_stream.png",
	"application/postscript"				=>	"application_octet_stream.png",
	"application/rtf"						=>	"text_rtf.png",
	"application/set-payment-initiation"	=>	"application_octet_stream.png",
	"application/set-registration-initiation"=>	"application_octet_stream.png",
	"application/vnd.ms-excel"				=>	"application_vnd.ms_excel.png",
	"application/vnd.ms-pkicertstore"		=>	"application_octet_stream.png",
	"application/vnd.ms-pkiseccat"			=>	"application_octet_stream.png",
	"application/vnd.ms-pkistl"				=>	"application_octet_stream.png",
	"application/vnd.ms-powerpoint"			=>	"application_vnd.ms_powerpoint.png",
	"application/vnd.ms-project"			=>	"application_octet_stream.png",
	"application/vnd.ms-works"				=>	"application_octet_stream.png",
	"application/winhlp"					=>	"application_octet_stream.png",
	"application/x-bcpio"					=>	"application_octet_stream.png",
	"application/x-cdf"						=>	"application_octet_stream.png",
	"application/x-compress"				=>	"application_x_archive.png",
	"application/x-compressed"				=>	"application_x_archive.png",
	"application/x-cpio"					=>	"application_octet_stream.png",
	"application/x-csh"						=>	"application_octet_stream.png",
	"application/x-director"				=>	"application_octet_stream.png",
	"application/x-dvi"						=>	"application_octet_stream.png",
	"application/x-gtar"					=>	"application_octet_stream.png",
	"application/x-gzip"					=>	"application_octet_stream.png",
	"application/x-hdf"						=>	"application_octet_stream.png",
	"application/x-internet-signup"			=>	"application_octet_stream.png",
	"application/x-iphone"					=>	"application_octet_stream.png",
	"application/x-javascript"				=>	"application_x_javascript.png",
	"application/x-latex"					=>	"application_octet_stream.png",
	"application/x-msaccess"				=>	"application_octet_stream.png",
	"application/x-mscardfile"				=>	"application_octet_stream.png",
	"application/x-msclip"					=>	"application_octet_stream.png",
	"application/x-msdownload"				=>	"application_octet_stream.png",
	"application/x-msmediaview"				=>	"application_octet_stream.png",
	"application/x-msmetafile"				=>	"application_octet_stream.png",
	"application/x-msmoney"					=>	"application_octet_stream.png",
	"application/x-mspublisher"				=>	"application_octet_stream.png",
	"application/x-msschedule"				=>	"application_octet_stream.png",
	"application/x-msterminal"				=>	"application_octet_stream.png",
	"application/x-mswrite"					=>	"application_octet_stream.png",
	"application/x-perfmon"					=>	"application_octet_stream.png",
	"application/x-php"						=>	"application_x_php.png",
	"application/x-pkcs12"					=>	"application_octet_stream.png",
	"application/x-pkcs7-certificates"		=>	"application_octet_stream.png",
	"application/x-pkcs7-certreqresp"		=>	"application_octet_stream.png",
	"application/x-pkcs7-mime"				=>	"application_octet_stream.png",
	"application/x-pkcs7-signature"			=>	"application_octet_stream.png",
	"application/x-sh"						=>	"application_octet_stream.png",
	"application/x-shar"					=>	"application_octet_stream.png",
	"application/x-stuffit"					=>	"application_octet_stream.png",
	"application/x-sv4cpio"					=>	"application_octet_stream.png",
	"application/x-sv4crc"					=>	"application_octet_stream.png",
	"application/x-tar"						=>	"application_x_archive.png",
	"application/x-tcl"						=>	"application_octet_stream.png",
	"application/x-tex"						=>	"application_octet_stream.png",
	"application/x-texinfo"					=>	"application_octet_stream.png",
	"application/x-troff"					=>	"application_octet_stream.png",
	"application/x-troff-man"				=>	"application_octet_stream.png",
	"application/x-troff-me"				=>	"application_octet_stream.png",
	"application/x-troff-ms"				=>	"application_octet_stream.png",
	"application/x-ustar"					=>	"application_octet_stream.png",
	"application/x-wais-source"				=>	"application_octet_stream.png",
	"application/x-x509-ca-cert"			=>	"application_octet_stream.png",
	"application/xml"						=>	"application_vnd.ms_excel.png",
	"application/ynd.ms-pkipko"				=>	"application_octet_stream.png",
	"application/zip"						=>	"application_x_archive.png",
	"audio/basic"							=>	"audio_basic.png",
	"audio/mid"								=>	"audio_basic.png",
	"audio/mpeg"							=>	"audio_basic.png",
	"audio/x-aiff"							=>	"audio_basic.png",
	"audio/x-mpegurl"						=>	"audio_basic.png",
	"audio/x-ms-wma"						=>	"audio_basic.png",
	"audio/x-pn-realaudio"					=>	"audio_basic.png",
	"audio/x-wav"							=>	"audio_basic.png",
	"image/bmp"								=>	"image_x_generic.png",
	"image/cis-cod"							=>	"image_x_generic.png",
	"image/gif"								=>	"image_x_generic.png",
	"image/ief"								=>	"image_x_generic.png",
	"image/jpeg"							=>	"image_x_generic.png",
	"image/pipeg"							=>	"image_x_generic.png",
	"image/tiff"							=>	"image_x_generic.png",
	"image/x-cmu-raster"					=>	"image_x_generic.png",
	"image/x-cmx"							=>	"image_x_generic.png",
	"image/x-icon"							=>	"image_x_generic.png",
	"image/x-portable-anymap"				=>	"image_x_generic.png",
	"image/x-portable-bitmap"				=>	"image_x_generic.png",
	"image/x-portable-graymap"				=>	"image_x_generic.png",
	"image/x-portable-pixmap"				=>	"image_x_generic.png",
	"image/x-rgb"							=>	"image_x_generic.png",
	"image/x-xbitmap"						=>	"image_x_generic.png",
	"image/x-xpixmap"						=>	"image_x_generic.png",
	"image/x-xwindowdump"					=>	"image_x_generic.png",
	"message/rfc822"						=>	"application_octet_stream.png",
	"text/css"								=>	"text_css.png",
	"text/csv"								=>	"text_csv.png",
	"text/h323"								=>	"application_octet_stream.png",
	"text/html"								=>	"text_html.png",
	"text/iuls"								=>	"text_plain.png",
	"text/plain"							=>	"text_plain.png",
	"text/richtext"							=>	"text_rtf.png",
	"text/scriptlet"						=>	"text_plain.png",
	"text/tab-separated-values"				=>	"text_csv.png",
	"text/webviewhtml"						=>	"text_html.png",
	"text/x-component"						=>	"text_plain.png",
	"text/x-setext"							=>	"text_plain.png",
	"text/x-vcard"							=>	"text_x_vcard.png",
	"video/mpeg"							=>	"video.png",
	"video/quicktime"						=>	"video.png",
	"video/x-la-asf"						=>	"video.png",
	"video/x-ms-asf"						=>	"video.png",
	"video/x-ms-wmv"						=>	"video.png",
	"video/x-msvideo"						=>	"video.png",
	"video/x-sgi-movie"						=>	"video.png",
	"x-world/x-vrml"						=>	"application_octet_stream.png"
);

/**
 * Get mime and icon from file.
 *
 * @param string $file The file name/reference
 * 
 * @return Array containing mime (string), icon (image name) 
 */
function comodojo_mimeByFile($file) {
	if (function_exists("finfo_open")) {
		$comodojo_finfo = finfo_open(FILEINFO_MIME_TYPE);
		$mime = finfo_file($comodojo_finfo, $file);
		$icon = comodojo_iconByMime($mime);
		finfo_close($comodojo_finfo);
	}
	elseif (function_exists("mime_content_type")) {
		$mime = mime_content_type($file);
		$icon = comodojo_iconByMime($mime);
	}
	else {
		$ext = explode('.',$file);
		$ext = $ext[count($ext)-1];
		if (isset($comodojo_mimeTypes[$ext])) {
			$mime = $comodojo_mimeTypes[$ext]['mime'];
			$icon = $comodojo_mimeTypes[$ext]['icon'];
		}
		else {
			$mime = "application/octet-stream";
			$icon = "application_octet_stream.png";
		}
	}
	return Array($mime, $icon);
}

/**
 * Get icon strarting from mime.
 *
 * @param string $mime The mime type
 *
 * @return Icon for mime (image name)
 */
function comodojo_iconByMime($mime) {
	return isset($comodojo_mimeIcons[$mime]) ? $comodojo_mimeIcons[$mime] : "application_octet_stream.png";
}

/**
 * Sanity check for CoMoDojo loader
 * 
 * @define function loadHelper_mime_types
 */
function loadHelper_mime_types() { return false; }

?>